Bash script that transfers a file from our client to a server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -3,6 +3,11 @@
 
 if [ "$#" -lt 4 ]; then
     echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+if scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/; then
+    echo "Successful"
 else
-    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
+    echo "Fail"
 fi
